# Application settings available as Rails.application.config.settings
#
# All values in this file are namespaced under Rails.application.config.settings
# and will not conflict with other configuration values in Rails.application.config.
# Settings are manually applied to the correct config var as needed in specific initializers.
# e.g. config/initializers/devise.rb

common: &common
  # Downcased and trimmed app name for namespaces.
  # Safest to start with a letter rather than a number.
  # See locales/en.yml for setting your app's user facing brand name.
  app_name: 'pygoogle_demo'

  social:
    facebook: 'https://www.facebook.com/KHongSanFrancisco'
    twitter: 'https://twitter.com/KHongTwit'
    google_plus: 'google.com/+KHongSanFrancisco'
    linkedin: 'www.linkedin.com/in/KHongSanFrancisco'

  contact:
    email: 'KHongSanFrancisco@gmail.com'
    phone: '777-777-7777'

  session:
    key: '_pygoogle_session'
    expire_after: <%= 30.days %>

  rack:
    # Timeout request after 20 seconds
    timeout: 20

  mail:
    layout: 'emails/email'
    from: 'KHongSanFrancisco@gmail.com'

  SENDMAIL_USERNAME: 'KHongSanFrancisco@gmail.com'
  #SENDMAIL_PASSWORD: 'aaa'

# Default ENV vars.
# Set to development values for convenience and override in production by setting ENV on the server.
# As a best practice, do not put production values in this file for security reasons.
default_env: &default_env
  # From address to use when sending email
  #MAIL_HOST: 'localhost:3000'
  #MAIL_HOST: 'pygoogle.com'

  # Host used to determine direct requests vs CDN.
  # See RobotsController.
  CANONICAL_HOST: 'pygoogle.herokuapp.com'

  #AUTH_FACEBOOK_KEY: '47'
  #AUTH_FACEBOOK_SECRET: 'f7'
  #AUTH_TWITTER_KEY: 'ye'
  #AUTH_TWITTER_SECRET: 'jr'

  # Devise password encryption keys.
  # Channging the keys will invalidate user passwords,
  # forcing users to use the forgot password feature.
  # TODO: make new keys with `rake secret`
  DEVISE_SECRET_KEY: '7da7ce94b67dcb951aba685032aa7ddc17ae2551a7a11b60369eff65f1c3cc0a5525c93900b6315daf1558b973d7f5c0b6e80addd61225d6a23694a5fb8ff83e'
  DEVISE_PEPPER: 'f23254b349cb3712c8c31dbdc4bb40555b0cd2ca9de98a15821ba5c2cb7d232b352e7f992bb8345dc53a2b4091f6b9dd1531bdaf1f1ae516d698e9f870d4e69c'

  # Signed cookie encryption key.
  # TODO: make new key with `rake secret`
  # SECRET_KEY_BASE: '16e628ec083d6127ca30716ac69c578ba47a900702f0d498c149b87d06eeebd1bc0be22929e16e2180cb137e9be8bc7f77dd3b9c13fbb306330bb6450cfbc051'

  # Redis server used by Sidekiq, cache, etc.
  REDIS_URL: 'redis://localhost:6379/0'

  # Airbrake/Errbit configuration
  AIRBRAKE_API_KEY: ''
  AIRBRAKE_HOST: ''


development:
  <<: *common
  env:
    <<: *default_env
    ALLOW_EMAIL_PREVIEW: true

test:
  <<: *common
  env:
    <<: *default_env

staging:
  <<: *common
  env:
    <<: *default_env

production:
  <<: *common
  env:
    # Set dummy key so rake assets:precompile succeeds
    DEVISE_SECRET_KEY: ''
